In [ ]:
import numpy as np
ali = np.load("/root/autodl-tmp/pixel3dmm/data/cap4d_format/00003/fit.npz")
fit = np.load("/root/autodl-tmp/pixel3dmm/data/cap4d_format/00002/fit.npz")

for key,v in ali.items():
    print(key)
    print(v)
    print(v.shape)

for key,v in fit.items():
    print(key)
    print(v)
    print(v.shape)

gaze
[[[-0.02290539  0.09459086]
  [-0.3924077   0.07910572]
  [ 1.0107588  -0.06162583]
  [-0.65259     0.06022342]]]
(1, 4, 2)
gaze_confidences
[[[0.00575179 0.00396784]
  [0.00555231 0.00271566]
  [0.02376175 0.01116896]
  [0.00875973 0.01243593]]]
(1, 4, 2)
crop_boxes
[[[110 320 550 760]
  [185 368 657 840]
  [ 88 414 562 888]
  [200 372 656 828]]]
(1, 4, 4)
valid_mask
[[ True  True  True  True]]
(1, 4)
vertex_coords
[[[[474.93515 543.288  ]
   [474.65573 545.5318 ]
   [475.7495  544.3084 ]
   ...
   [282.7157  486.3568 ]
   [282.68488 486.3418 ]
   [282.6513  486.32556]]

  [[541.0427  603.64856]
   [539.4068  605.62146]
   [539.9789  603.92017]
   ...
   [411.85162 550.97107]
   [411.8203  550.9542 ]
   [411.78622 550.9361 ]]

  [[491.87308 651.14685]
   [492.20743 653.5049 ]
   [493.1936  652.0537 ]
   ...
   [228.10435 605.9811 ]
   [228.07747 605.9685 ]
   [228.04823 605.95483]]

  [[492.01675 602.10504]
   [490.5212  604.47546]
   [491.55435 602.96014]
   ...
   [449.84808 54