In [1]:
import numpy as np
ali = np.load("/root/autodl-tmp/cap4d/examples/input/felix/alignment.npz")
fit = np.load("/root/autodl-tmp/cap4d/examples/input/lincoln/fit.npz")

for key,v in ali.items():
    print(key)
    print(v)
    print(v.shape)

for key,v in fit.items():
    print(key)
    print(v)
    print(v.shape)

gaze
[[[-0.10076334  0.06605275]]]
(1, 1, 2)
gaze_confidences
[[[0.03276064 0.03621367]]]
(1, 1, 2)
crop_boxes
[[[ 51  77 513 539]]]
(1, 1, 4)
valid_mask
[[ True]]
(1, 1)
vertex_coords
[[[[426.8716  305.53638]
   [426.0132  307.6417 ]
   [426.28815 306.55655]
   ...
   [235.99774 277.10138]
   [235.97023 277.09213]
   [235.94026 277.08215]]]]
(1, 1, 5023, 2)
vertex_confidences
[[[[10.468084]
   [ 9.6123  ]
   [ 9.374962]
   ...
   [15.728384]
   [15.815648]
   [15.910526]]]]
(1, 1, 5023, 1)
resolutions
[[800 600]]
(1, 2)
n_timesteps
1
()
n_views
1
()
camera_order
['cam0']
(1,)
fx
[[2169.0063]]
(1, 1)
fy
[[2169.0063]]
(1, 1)
cx
[[300.]]
(1, 1)
cy
[[400.]]
(1, 1)
extr
[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]]]
(1, 4, 4)
shape
[ 0.41987428 -1.1822004  -1.3931065   0.7980182   1.1856676  -0.04543107
 -1.0955161   1.6408637  -0.40003303  0.11283074  0.8227636  -1.4728109
  0.60218424  0.63291454  2.0418463   2.142694   -0.70079327  0.97626555
 -1.1778338  -0.5308363  